### ISSUE TITLE
Hardcoded field name in calendar creation

### ISSUE THREAD

**Issue by AndrewGri** [qlikperf/TSEEQ#6]
Hello.

In current version of Common/Include/CreateCalendarTable.txt main calendar field name is hardcoded as **Date**. So if you want master calendar table to be connected to the fact table, you should name fact table date field as **Date**. I suggest to change the line 71 in CreateCalendarTable.txt to look like this:
`Date (TempDate) AS [$(vCCQ_CalendarName)$(vTSEEQ_FactTableDateField)],`
The result is master calendar table has the date field with the same name as fact table's date field.

**Comment by qlikperf** [comment]
Hi @AndrewGri ,

Thank for your suggestion.  Thinking this through, maybe line 71 of CreateCalendarTable.txt  should be simply:
` Date (TempDate) AS [$(vTSEEQ_FactTableDateField)],`
rather than the slightly more complex
`Date (TempDate) AS [$(vCCQ_CalendarName)$(vTSEEQ_FactTableDateField)],
`

If CreateCalendarQvd is invoked as follows:
`      call CreateCalendarQvd('Order', 'KEEP');`
then the more complex option, with `$(vCCQ_CalendarName),` would result in the date field in the Calendar being named **OrderDate**, which would not link to **Date** in the **Orders** table (here I am referring specifically TSEEQ Sales Sample\Sales Dashboard.qvf  as the example)

**Comment by qlikperf** [comment]
Resolved in v4.1.1 on 2020-11-26.
